### Environment
:atlanta_url = localhost:7081
# :atlanta_url = ca2-p1r01-srv009.ca2.internal.zone:11992

# POST Shop
:origin = "MEL"
:destination = "LAX"
:departure_date = "2019-07-01"
# :return_date = "2019-07-07"
# TODO: Add provider parameters
POST http://:atlanta_url/api/v1/query
Content-Type: application/json

{
  "query": {
    "origin_type": "airport",
    "origin": :origin ,
    "destination_type": "airport",
    "destination": :destination ,
    "departure_date": :departure_date ,
    "filters": {
			"max_stops": 2,
			"exclude_validating_carriers": ["O1"],
			"exclude_marketing_carriers": ["O1"]
		},
		"user_information": {
			"ipAddress": "107.77.227.18",
			"userCountry": "United States"
		},
		"passengers": {
			"ADT": 1
		}
  },
  "provider": {
    "ShopProviderConfig": "Travelport",
    "base": {
			"ProviderBase": "TravelportProvider",
			"pcc": "8Z2T",
			"gds": {
				"TravelportGds": "Galileo"
			}
		}
  },
  "pointOfSale": {
    "country": "US",
    "currency": "USD"
  },
  "shopContext": {
		"ticketlessCarriers": [],
		"blacklists": {
			"validatingCarriers": [],
			"marketingCarriers": [],
			"airports": []
		}
	},
	"log_retention": "Forever"
}

