# Environment
:madrid_url = localhost:7081
# :madrid_url = ca2-p1r03-srv024.ca2.internal.zone:11988
# POST Shop
:origin = "LHR"
:destination = "JFK"
:departure_date = "2019-07-01"
# TODO: Add provider parameters
POST http://:madrid_url/api/v1/query
Content-Type: application/json

{
    "origin_type": "airport",
    "origin": :origin ,
    "destination_type": "airport",
    "destination": :destination ,
    "departure_date": :departure_date ,
    "filters": {
			"max_stops": 2,
			"exclude_validating_carriers": [],
			"exclude_marketing_carriers": []
		},
		"user_information": {
			"ipAddress": "107.77.227.18",
			"userCountry": "United States"
		},
		"passengers": {
			"ADT": 1
		}
  },
  "provider": {
    "ShopProviderConfig": "Travelfusion",
    "base": {
			"ProviderBase": "TravelfusionProvider",
			"pcc": "2G5K",
			"gds": {
				"TravelportGds": "Apollo"
			}
		}
  },
  "pointOfSale": {
    "country": "US",
    "currency": "USD"
  },
  "shopContext": {
		"ticketlessCarriers": [],
		"blacklists": {
			"validatingCarriers": [],
			"marketingCarriers": [],
			"airports": []
		}
	},
	"log_retention": "Forever"
}
